### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by yuliang-hk** [dievus/printspoofer#2]
Last privilege escalation for this room use command: PrintSpoofer.exe -i -c cmd
Error: c:inetpubwwwroot for this version
t4wrksvPrintSpoofer.exe is not compatible with the version of Windows you are running. Check your computer's system information, and then contact the software publisher.
help me

**Comment by dievus** [comment]
This is a user error issue in how you transferred the file, not an issue with the binary itself.

Closing.
